### ISSUE TITLE
agilent  thermo

### ISSUE THREAD

**Issue by skywalker-andy** [Jack-Sun-007/Agilent_wkl2excel#1]
看到你分享的很多项目都是跟thermo的文件有关？要是能出一个将thermo产生的谱图（raw）格式的文件，将谱图数据批量导出成excel就好了；
这个关于安捷伦谱图数据导出的工作也很棒！

**Comment by Jack-Sun-007** [comment]
Thermo原始数据（raw）格式的文件可以用[pymsfilereader](https://github.com/frallain/pymsfilereader)库进行读取，结合pandas库数据清洗后导Excel表。由于不同采集方式的谱图数据稍有不同（全一级谱图、一二级谱图混合等），数据清洗部分会有所不同，可以自行尝试编写。

**Comment by Jack-Sun-007** [comment]
> 看到你分享的很多项目都是跟thermo的文件有关？要是能出一个将thermo产生的谱图（raw）格式的文件，将谱图数据批量导出成excel就好了； 这个关于安捷伦谱图数据导出的工作也很棒！

Thermo原始数据（raw）格式的文件可以用[pymsfilereader](https://github.com/frallain/pymsfilereader)库进行读取，结合pandas库数据清洗后导Excel表。由于不同采集方式的谱图数据稍有不同（全一级谱图、一二级谱图混合等），数据清洗部分会有所不同，可以自行尝试编写。

**Comment by skywalker-andy** [comment]
> > 看到你分享的很多项目都是跟thermo的文件有关？要是能出一个将thermo产生的谱图（raw）格式的文件，将谱图数据批量导出成excel就好了； 这个关于安捷伦谱图数据导出的工作也很棒！
> 
> Thermo原始数据（raw）格式的文件可以用[pymsfilereader](https://github.com/frallain/pymsfilereader)库进行读取，结合pandas库数据清洗后导Excel表。由于不同采集方式的谱图数据稍有不同（全一级谱图、一二级谱图混合等），数据清洗部分会有所不同，可以自行尝试编写。

**Comment by skywalker-andy** [comment]
好的好的，谢谢你！！！我才知道pymsfilereader这个东西
